"""FastMCP wrapper runtime generator (T042).

Produces a self-contained FastMCP-compatible Python module from a canonical
``Wrapper`` spec.  The generated module registers each stage of the wrapper
as an MCP tool, with Pydantic-annotated input models derived from the wrapper's
declared input fields.

This is one of the host-native "derived outputs" described in FR-008: for the
OpenClaw adapter, wrapper runtimes are generated Python files that the adapter
deploys into the agent skill tree.
"""

from __future__ import annotations

import textwrap
from typing import Any

from clawwrap.adapters.base import AdapterProtocol
from clawwrap.model.wrapper import Wrapper

# Python type mapping from clawwrap TypeRef strings to Python annotations.
_TYPE_MAP: dict[str, str] = {
    "string": "str",
    "str": "str",
    "integer": "int",
    "int": "int",
    "float": "float",
    "bool": "bool",
    "boolean": "bool",
    "list": "list[Any]",
    "dict": "dict[str, Any]",
    "any": "Any",
}

_DEFAULT_TYPE = "Any"


def generate_mcp_runtime(wrapper: Wrapper, adapter: AdapterProtocol) -> str:
    """Generate a FastMCP-compatible Python module for *wrapper*.

    The output is a fully self-contained ``.py`` file that:
    - Imports FastMCP and creates a ``mcp`` app instance.
    - Registers one ``@mcp.tool()`` per wrapper stage.
    - Uses Pydantic ``BaseModel`` for structured inputs.
    - Embeds wrapper metadata as module-level docstring and constants.

    Args:
        wrapper: The canonical Wrapper spec.
        adapter: Host adapter providing identity config metadata.

    Returns:
        Generated Python source code as a string.
    """
    config = adapter.get_approval_identity_config()
    adapter_name = config.source_type

    sections: list[str] = [
        _generate_header(wrapper, adapter_name),
        _generate_imports(),
        _generate_constants(wrapper, adapter_name),
        _generate_input_model(wrapper),
        _generate_mcp_instance(wrapper),
        _generate_stage_tools(wrapper),
        _generate_main_guard(),
    ]
    return "\n\n".join(s for s in sections if s.strip())


# ---------------------------------------------------------------------------
# Section generators
# ---------------------------------------------------------------------------


def _generate_header(wrapper: Wrapper, adapter_name: str) -> str:
    """Generate module docstring with wrapper metadata."""
    return textwrap.dedent(f'''\
        """FastMCP runtime for wrapper: {wrapper.name}

        Version     : {wrapper.version}
        Schema      : {wrapper.schema_version}
        Description : {wrapper.description}
        Adapter     : {adapter_name}
        Approval    : {wrapper.approval_role.name}

        Auto-generated by clawwrap.generators.fastmcp — do not edit manually.
        """
    ''')


def _generate_imports() -> str:
    """Generate import block."""
    return textwrap.dedent("""\
        from __future__ import annotations

        from typing import Any

        from fastmcp import FastMCP
        from pydantic import BaseModel
    """)


def _generate_constants(wrapper: Wrapper, adapter_name: str) -> str:
    """Generate module-level constants for wrapper metadata."""
    return textwrap.dedent(f"""\
        WRAPPER_NAME: str = "{wrapper.name}"
        WRAPPER_VERSION: str = "{wrapper.version}"
        ADAPTER_NAME: str = "{adapter_name}"
        APPROVAL_ROLE: str = "{wrapper.approval_role.name}"
    """)


def _generate_input_model(wrapper: Wrapper) -> str:
    """Generate a Pydantic BaseModel for wrapper inputs."""
    if not wrapper.inputs:
        return textwrap.dedent("""\
            class WrapperInput(BaseModel):
                \"\"\"Input model for this wrapper (no declared inputs).\"\"\"
        """)

    field_lines: list[str] = []
    for inp in wrapper.inputs:
        py_type = _TYPE_MAP.get(inp.type.lower(), _DEFAULT_TYPE)
        if inp.required:
            field_lines.append(f"    {inp.name}: {py_type}")
        else:
            field_lines.append(f"    {inp.name}: {py_type} | None = None")

    fields_block = "\n".join(field_lines)
    return textwrap.dedent(f"""\
        class WrapperInput(BaseModel):
            \"\"\"Input model for wrapper '{wrapper.name}'.\"\"\"

        {fields_block}
    """)


def _generate_mcp_instance(wrapper: Wrapper) -> str:
    """Generate the FastMCP app instance."""
    return textwrap.dedent(f"""\
        mcp: FastMCP = FastMCP(
            name="{wrapper.name}",
            version="{wrapper.version}",
        )
    """)


def _generate_stage_tools(wrapper: Wrapper) -> str:
    """Generate one @mcp.tool() per declared wrapper stage."""
    if not wrapper.stages:
        return textwrap.dedent("""\
            @mcp.tool()
            def run(inputs: WrapperInput) -> dict[str, Any]:
                \"\"\"Execute this wrapper (no explicit stages declared).\"\"\"
                return {"wrapper": WRAPPER_NAME, "inputs": inputs.model_dump()}
        """)

    tool_blocks: list[str] = []
    for stage in wrapper.stages:
        phase_name = stage.phase.value
        fn_name = f"stage_{phase_name}"
        expects_desc = _describe_type_ref(stage.expects)
        produces_desc = _describe_type_ref(stage.produces)

        tool_block = textwrap.dedent(f"""\
            @mcp.tool()
            def {fn_name}(inputs: WrapperInput) -> dict[str, Any]:
                \"\"\"Execute {phase_name} phase for '{WRAPPER_NAME_PLACEHOLDER}'.

                Expects : {expects_desc}
                Produces: {produces_desc}
                \"\"\"
                return {{
                    "phase": "{phase_name}",
                    "wrapper": WRAPPER_NAME,
                    "inputs": inputs.model_dump(),
                    "status": "ok",
                }}
        """).replace("WRAPPER_NAME_PLACEHOLDER", wrapper.name)
        tool_blocks.append(tool_block)

    return "\n".join(tool_blocks)


def _generate_main_guard() -> str:
    """Generate the standard ``if __name__ == '__main__'`` guard."""
    return textwrap.dedent("""\
        if __name__ == "__main__":
            mcp.run()
    """)


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _describe_type_ref(type_ref: dict[str, Any] | str | None) -> str:
    """Convert a TypeRef dict or string to a short description string.

    Args:
        type_ref: TypeRef from a StageParticipation (expects/produces).

    Returns:
        Human-readable type description.
    """
    if type_ref is None:
        return "unspecified"
    if isinstance(type_ref, str):
        return type_ref
    if isinstance(type_ref, dict):
        if "type" in type_ref:
            return str(type_ref["type"])
        return str(type_ref)
    return str(type_ref)


# Make WRAPPER_NAME_PLACEHOLDER visible to f-string at call site.
WRAPPER_NAME_PLACEHOLDER = "WRAPPER_NAME_PLACEHOLDER"
